version: '3.8'

services:
  blps_3_notification_service:
    image: openjdk:17-oracle
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: itmo
      POSTGRES_USER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: postgres
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    container_name: blps_3_notification_service
    volumes:
      - ./blps_3_notification_service.jar:/home/blps_3_notification_service.jar
    command: ["java", "-jar", "/home/blps_3_notification_service.jar"]
    ports:
      - "2222:2222"
