version: '3.8'

services:
  postgres:
    image: postgres:11
    environment:
      POSTGRES_DB: itmo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - drain-network

  zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - drain-network

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    networks:
      - drain-network

  blps-3-notification-service:
    image: openjdk:17-oracle
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: itmo
      POSTGRES_USER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: postgres
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - postgres
      - kafka
    container_name: blps-3-notification-service
    volumes:
      - ./blps-3-notification-service.jar:/home/blps-3-notification-service.jar
    command: ["java", "-jar", "/home/blps-3-notification-service.jar"]
    ports:
      - "2222:2222"
    networks:
      - drain-network

  blps-3-payment-service:
    image: openjdk:17-oracle
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: itmo
      POSTGRES_USER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: postgres
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - postgres
      - kafka
    container_name: blps-3-payment-service
    volumes:
      - ./blps-3-payment-service.jar:/home/blps-3-payment-service.jar
    command: ["java", "-jar", "/home/blps-3-payment-service.jar"]
    ports:
      - "3333:3333"
    networks:
      - drain-network

  buisness-logic-lab-3:
    image: openjdk:17-oracle
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: itmo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      PAYMENT_HOST_PORT: blps-3-payment-service:3333
    depends_on:
      - postgres
      - kafka
      - blps-3-payment-service
      - blps-3-notification-service
    container_name: buisness-logic-lab-3
    volumes:
      - ./buisness-logic-lab-3.jar:/home/buisness-logic-lab-3.jar
    command: ["java", "-jar", "/home/buisness-logic-lab-3.jar"]
    ports:
      - "8135:8135"
    networks:
      - drain-network

networks:
  drain-network:
    driver: bridge
