version: '3.8'

services:
  postgres:
    image: postgres:11
    environment:
      POSTGRES_DB: itmo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9797:9797"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9797
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  blps_3_notification_service:
    image: openjdk:17-oracle
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: itmo
      POSTGRES_USER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: postgres
      KAFKA_BOOTSTRAP_SERVERS: kafka:9797
    depends_on:
      - postgres
      - kafka
    container_name: blps_3_notification_service
    volumes:
      - ./blps_3_notification_service.jar:/home/blps_3_notification_service.jar
    command: ["java", "-jar", "/home/blps_3_notification_service.jar"]
    ports:
      - "2222:2222"

  blps_3_payment_service:
    image: openjdk:17-oracle
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: itmo
      POSTGRES_USER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: postgres
      KAFKA_BOOTSTRAP_SERVERS: kafka:9797
    depends_on:
      - postgres
      - kafka
    container_name: blps_3_payment_service
    volumes:
      - ./blps_3_payment_service.jar:/home/blps_3_payment_service.jar
    command: ["java", "-jar", "/home/blps_3_payment_service.jar"]
    ports:
      - "3333:3333"

  buisness-logic-lab-3:
    image: openjdk:17-oracle
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: itmo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
      KAFKA_BOOTSTRAP_SERVERS: kafka:9797
      PAYMENT_HOST_PORT: blps_3_payment_service:3333
    depends_on:
      - postgres
      - kafka
      - blps_3_payment_service
      - blps_3_notification_service
    container_name: buisness-logic-lab-3
    volumes:
      - ./buisness-logic-lab-3.jar:/home/buisness-logic-lab-3.jar
    command: ["java", "-jar", "/home/buisness-logic-lab-3.jar"]
    ports:
      - "8135:8135"
